### ISSUE TITLE
15份数据后，data路由没有显示内容

### ISSUE THREAD

**Issue by aaq1adqwe** [javahuang/SurveyKing#10]
survey/nogrIy/data

数据多了好像就显示不出来了

**Comment by aaq1adqwe** [comment]
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
        at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
        at cn.surveyking.server.impl.AnswerServiceImpl.lambda$setAnswerTypeInfo$6(AnswerServiceImpl.java:105)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at cn.surveyking.server.impl.AnswerServiceImpl.setAnswerTypeInfo(AnswerServiceImpl.java:101)
        at cn.surveyking.server.impl.AnswerServiceImpl.setAnswerExtraInfo(AnswerServiceImpl.java:91)
        at cn.surveyking.server.impl.AnswerServiceImpl.lambda$listAnswer$0(AnswerServiceImpl.java:68)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at cn.surveyking.server.impl.AnswerServiceImpl.listAnswer(AnswerServiceImpl.java:68)
        at cn.surveyking.server.impl.AnswerServiceImpl$$FastClassBySpringCGLIB$$9117d5a.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
        at cn.surveyking.server.impl.AnswerServiceImpl$$EnhancerBySpringCGLIB$$4a0f0fb.listAnswer(<generated>)
        at cn.surveyking.server.api.AnswerApi.listAnswer(AnswerApi.java:31)
        at cn.surveyking.server.api.AnswerApi$$FastClassBySpringCGLIB$$b83db177.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:61)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
        at cn.surveyking.server.api.AnswerApi$$EnhancerBySpringCGLIB$$67a6f00f.listAnswer(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1064)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:228)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:113)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:113)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:121)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at cn.surveyking.server.core.security.JwtTokenFilter.doFilterInternal(JwtTokenFilter.java:65)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1723)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

**Comment by javahuang** [comment]
@aaq1adqwe 能给你问卷的 json 贴一下吗

**Comment by aaq1adqwe** [comment]
{"hmch":{"u8oa":"1"},"u6od":{"gxn1":"XX单位"},"cwq5":{"fjgf":"xx官网"},"i2kp":{"ap9y":"冰桑","sj3v":"13333333333"},"igc3":[{"hheu":"1","jza4":"91beta测试系统","ybpz":"b/s","5kyh":"多媒体业务","ah4x":"xx","siax":"2级","263i":"阿里云","jo92":"托管"},{}],"38v7":{"zgvk":"xx"},"1g0z":{"cpbx":true},"7mka":{"lozv":"xx"},"50w9":{"jpnm":"多媒体"},"w1cw":{"6uos":"2"},"dfsl":{"905t":true},"n3za":{"6ndz":"1"},"xvx6":{"lhsd":"1"},"9cq6":[{"6jbq":"1","tzjw":"ae8l","nr42":"xx系统"},{}],"j8la":{"5bop":true},"9sg4":{"m516":"xx","05iw":"xxx"},"o7l7":{"ktj4":true},"qycs":{"ngvn":true},"migm":{"39co":true},"r6h4":{"1udc":true},"re95":{"73z0":true},"woiv":{"2or4":true},"7w4h":{"4b0j":true},"pmn0":{"v2om":true},"bp4j":{"yny9":true},"t305":{"hutf":true},"cpb5":{"xp05":true},"mklj":{"bhij":true},"mp8s":{"zjbq":true},"5mbz":{"52kk":true},"7zek":{"6rg0":"200","a0t2":"100","g7uv":"50","p35k":"100"},"kp1s":{"tmfb":"200"},"jis2":{"26c2":true},"idqi":{"uy3p":true},"vr93":{"oaap":true},"ce65":{"fgly":true},"9sf6":{"bp6v":true},"3bo9":{"wp9i":true},"0406":{"voe0":"1"},"j2b2":{"ahyn":"1"},"5rse":{"vdim":true},"3v2k":{"l89u":true},"ehbv":{"txs8":true},"23ol":{"kfyh":true},"ng01":{"minb":"200"},"rs06":{"36w2":true},"03am":{"vqvp":true},"gmkz":{"fpwx":true},"ov7k":{"v2ci":true},"icgj":{"yk5t":"xx","jeva":"xx"},"53hs":{"9cfs":true},"lee8":{"bxnx":true},"bku0":{"9nj6":true},"u1wj":{"2lyt":true,"lsei":true},"3ir1":{"hp7q":true},"cgqm":{"7ow2":true},"7pey":{"byqc":true},"onnz":{"93ef":true},"b19o":{"8via":true},"tmks":{"9wlx":true},"97wi":{"qh90":true},"jtks":{"cbhb":"1","zo1h":"1","z5n3":"1"},"2e0w":{"g8ft":true},"dbp1":{"f25b":true},"suyi":{"l9ch":"0"},"yi02":{"05sw":"1"},"gyzk":{"fwa6":true},"9aqa":{"fbmb":3,"sfxf":8,"wfo3":1},"bh6u":{"sj3p":true},"x10q":{"qgqr":true},"cr3a":{"ovo7":true},"q4p7":{"hgvx":"启明"},"j53q":{"xzlh":true},"s1e9":{"q0x3":true,"hzj9":true,"ckgc":true},"1apd":{"wqv9":true},"sncn":{"xeu4":true},"ooms":{"6gwl":true},"a630":{"beqw":true},"idyn":{"5ugz":true},"0le8":{"nva2":true},"dvjl":{"fb3f":true},"rkxa":{"93pm":"0","ydkc":"0","znr9":"1","tfsu":"0"},"m057":{"p5gv":"0","oj1s":"0","h6mo":"0","t8r1":"1"},"xjzz":{"3tci":true},"anu9":{"5fau":true},"457l":{"q74r":true},"sce2":{"9kp4":true},"0uxr":{"q6ga":true},"vjxe":{"ok0p":true},"7uex":{"mej2":true},"ijba":{"shjl":"x","6tj3":"x"},"g6fp":{"sc74":true},"728z":{"xed2":true},"qgcs":{"t9bh":""},"es3z":{"fiug":true},"xtxl":{"obq6":true},"3s20":{"dpo7":true},"dw80":{"joiw":true},"dnbk":{"ntht":true},"d57e":{"oaa1":true},"qb57":{"lyrm":true},"q5g9":{"9t2a":true},"zulh":{"fi40":""},"su97":{"o44g":true},"1vyv":{"ae2i":true},"048u":{"bfse":true},"0210":{"2xn2":true},"17lx":{"rmkp":true},"f1z8":{"h8rq":true},"ji7w":{"x46e":true},"16ty":{"6r1u":true},"1ums":{"qqep":"10","4vls":"0"},"myd5":{"iind":"10","ipnz":"10","25xh":"0","sjuy":"0"},"6ap0":{"xtfu":["1522860810378936321"]},"uawv":{"gniv":["1522860832008962049"]},"m7qw":{"6lgq":["1522860852003209217"]}}
